#!/usr/bin/env python3
"""Generate the built-in 16x16 OSD glyph ROM (Pillow + Noto Sans CJK SC).
The generated Verilog is checked in; TD and Icarus need no Python/font at build time.
Font pixels: SIL OFL 1.1; see docs/licenses/OSD_FONT_OFL.txt.
"""
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

MESSAGES = {
    'normal0': '图片 00/00  自动轮播：关闭',
    'normal1': '间隔：00秒  方向：正序',
    'init': '正在初始化TF卡',
    'volume': '正在读取FAT32分区',
    'scan': '正在扫描BMP图片',
    'load': '正在加载图片 00/00',
    'display': '正在准备显示',
    'error10': '错误10：需要FAT32格式',
    'error11': '错误11：未找到符合格式的图片',
    'error12': '错误12：图片数据异常',
    'error13': '错误13：文件簇链损坏',
    'error14': '错误14：读卡或缓存超时',
    'error15': '错误15：读取状态异常',
    'format': '根目录BMP：640x480，24位',
    'retry': '按KEY1重试，请检查TF卡',
}
EXTRA = '0123456789开启倒序轮播：' + ''.join(chr(i) for i in range(32,127))


def glyphs(font_path, font_index):
    font = ImageFont.truetype(str(font_path), 16, index=font_index)
    chars = [' '] + sorted(set(''.join(MESSAGES.values()) + EXTRA) - {' '})
    if len(chars) > 256:
        raise ValueError('glyph index exceeds eight bits')
    top = min(font.getbbox(ch)[1] for ch in chars if ch != ' ')
    bottom = max(font.getbbox(ch)[3] for ch in chars if ch != ' ')
    height = max(16, bottom - top)
    bitmaps = []
    for ch in chars:
        canvas = Image.new('L', (16, height), 0)
        x = round((16 - font.getlength(ch)) / 2)
        ImageDraw.Draw(canvas).text((x, -top), ch, font=font, fill=255)
        if height != 16:
            canvas = canvas.resize((16, 16), Image.Resampling.LANCZOS)
        bitmap = canvas.point(lambda v: 255 if v >= 105 else 0).convert('1')
        bitmaps.append(bitmap)
    return chars, bitmaps


def generate(font_path, font_index, output, preview=None):
    chars, bitmaps = glyphs(font_path, font_index)
    lines = [
        '// Generated by tools/generate_osd_font.py; built-in 16x16 UI subset.',
        '// Bitmap font derived from Noto Sans CJK SC, SIL OFL 1.1.',
        '// Copyright 2010-2012 Google Corporation; see docs/licenses/OSD_FONT_OFL.txt.',
        '// One synchronous pixel-clock read; bit 15 is the leftmost pixel.',
        'module osd_font16(input wire clk,input wire [15:0] codepoint,',
        ' input wire [3:0] row,output reg [15:0] pixels);',
        ' reg [7:0] glyph_index;',
        ' always @* begin',
        '  case(codepoint)',
    ]
    for idx, ch in enumerate(chars):
        lines.append(f"   16'h{ord(ch):04x}:glyph_index=8'd{idx}; // {ch}")
    lines += ['   default:glyph_index=0;', '  endcase', ' end',
              ' (* ram_style="bram" *) reg [15:0] font_rom[0:4095];',
              ' initial begin']
    for idx in range(256):
        if idx < len(chars):
            lines.append(f'  // Glyph {idx}: {chars[idx]}')
        for y in range(16):
            bits = 0
            if idx < len(chars):
                bits = sum((1 << (15-x)) for x in range(16) if bitmaps[idx].getpixel((x, y)))
            lines.append(f"  font_rom[{idx*16+y}]=16'h{bits:04x};")
    lines += [' end', ' always @(posedge clk) pixels<=font_rom[{glyph_index,row}];', 'endmodule', '']
    Path(output).write_text('\n'.join(lines), encoding='utf-8')
    if preview:
        # Preview exactly the generated monochrome pixels, not a separate text renderer.
        rows = [
            '图片 01/04  自动轮播：开启',
            '间隔：05秒  方向：正序',
            '正在扫描BMP图片',
            '错误14：读卡或缓存超时',
            '按KEY1重试，请检查TF卡',
        ]
        image = Image.new('RGB', (608, 160), '#000000')
        by_char = dict(zip(chars, bitmaps))
        for line, text in enumerate(rows):
            for column, ch in enumerate(text):
                mask = by_char[ch].convert('L')
                image.paste('#e8f4ff', (12+column*18, 12+line*28), mask)
        image.resize((1216, 320), Image.Resampling.NEAREST).save(preview)
    return len(chars)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', default='/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc')
    parser.add_argument('--font-index', type=int, default=2, help='SC is face 2 in Noto CJK TTC')
    parser.add_argument('--output', default=str(Path(__file__).resolve().parents[1]/'rtl/osd_font16.v'))
    parser.add_argument('--preview')
    args = parser.parse_args()
    count = generate(args.font, args.font_index, args.output, args.preview)
    print(f'Generated {count} glyphs: {args.output}')


if __name__ == '__main__':
    main()
